# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: ContactPage}
          - {label: Slug, name: slug, widget: hidden, default: 'contact'}
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: string}
          - {label: Address, name: address, widget: string}
          - {label: Phone, name: phone, widget: string}
          - {label: Email, name: email, widget: string}

      - file: "content/pages/casechange.md"
        label: "A Case For Change"
        name: "case-change-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: CaseChangePage}
          - {label: Slug, name: slug, widget: hidden, default: 'a-case-for-change'}
          - {label: Title, name: title, widget: string}
          - label: Section 1
            name: section1
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}
          - label: Icon Grid
            name: iconGrid
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Link, name: linkTo, widget: hidden, default: '#'}
              - label: Popup
                name: popupContent
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: content, widget: markdown}
          - label: Section 3
            name: section3
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Content, name: content, widget: markdown}

      - file: "content/pages/betterview.md"
        label: "A Better View"
        name: "betterview-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: BetterViewPage}
          - {label: Slug, name: slug, widget: hidden, default: 'a-better-view'}
          - {label: Title, name: title, widget: string}
          - label: Section 1
            name: section1
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Section 2
            name: section2
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Icon Grid
            name: iconGrid
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Image, name: image, widget: image}

      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: AboutPage}
          - {label: Slug, name: slug, widget: hidden, default: 'about'}
          - {label: Title, name: title, widget: string}
          - label: Section 1
            name: section1
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Slug, name: slug, widget: string}
              - {label: Image, name: image, widget: image}

      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: HomePage}
          - {label: Slug, name: slug, widget: hidden, default: ''}
          - {label: Title, name: title, widget: string}
          - label: Section 1
            name: section1
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Section 2
            name: section2
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Section 3
            name: section3
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Section 4
            name: section4
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Content, name: content, widget: markdown}


  - name: "team"
    label: "Team Bio"
    editor:
      preview: true
    folder: content/team
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: Template, name: template, widget: hidden, default: DefaultPage}
      - {label: Slug, name: slug, widget: string}
      - {label: Title, name: title, widget: string}
      - {label: Position, name: position, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Description, name: description, widget: markdown}


  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
